name: fk_action_sheet
description: A Flutter package for Action Sheet.
version: 2.0.0
homepage: https://github.com/flutter-fast-kit/fk_action_sheet.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter